language: node_js
node_js: stable
sudo: false

# Travis-CI Caching
cache:
  yarn: true
  directories:
    - node_modules

# S: Build Lifecycle
install:
- yarn

script:
- yarn build

branches:
  only:
  - master

deploy:
  provider: npm
  email: jmlsphere@gmail.com
  api_key:
    secure: XQz7V+ZSjmIqXu2v2134pkuL4DDKqpJfTjUF9Rh61YWCr0/a/5ixeHhZGPZjL/7kKYKb7w1MQxKkPaUZK+33WNTGM76XJO0zbX74ZGvUcssJOGhak3JjPAEFTTZmbowErrLIQ3UmrZgjC4ZSu+iJ6e9XMMihBiWOEVow0R1AjBAsjy/m3DqL8ne4BoqHgsnlrqf2qo3Zlvf7PFeOXL4XbGcIfiYv1BJX3mOYcJPbi96p9c3qLfrJXgSRf3IW9NFvwFE2W8fY7l9IFvTsMwQ11XIf98ibh2tbk2zPncgDhQ48pecMdSrBTwEM/jpLv9Qip8lal43PMpv6TqrmZ2/Gtk6o3wQP99+MMwowhmAz8R8QpADUX1zr8RxrYdCRT4utbwwoW5hq53AoVicADNfeoRoAZciSNyCctmugodKw0w91Tq9Iahh+Y5pKNI15Lc8jo1+xCIw/dGgIbk8JC5EwoAoyxK9Muua/Uncu33u72PJhjMio6m54l8j+IxaXuDuJjLobJ5ywbtPAUD9h99RtKEcjmTqDmDjJb3Xs52fcmn9DKDpd5JhP15OKw+WxaAEf4I4HRvbs69pyR9lpO+rjb2ZXYLS+mBgWuGLaWUCypYWy/wEgOFG5apqIygz9GnhH7stKUVjRXPd+boJSOjBp8zoy4QLBhH3CsLLdCkdGmjE=
  on:
    all_branches: true
